spring:
  application:
    name: Merkliste_2.0

logging:
  level:
    org.apache.http.wire: INFO
    de.theonebrack.merkliste_20: INFO

merkliste:
#  baseUrl: https://www.buecherhallen.de
  baseUrl: http://localhost:9090