spring:
  application:
    name: Merkliste_2.0

server:
  error:
    include-message: always

logging:
  level:
    org.apache.http.wire: INFO
    de.theonebrack.merkliste_20: INFO

merkliste:
  baseUrl: https://www.buecherhallen.de