name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set version
        run: echo "VERSION=$(cat version)" >> $GITHUB_ENV
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
      - name: Build with Gradle and prepare Docker files
        run: ./gradlew :backend:copyBackendJar :backend:copyDockerfiles
        env:
          CI: ""
      - name: Build and push Docker image
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY: docker.pkg.github.com
          DOCKERFILE: ${{ github.workspace }}/backend/build/docker/Dockerfile
          BUILD_PATH: ${{ github.workspace }}/backend/build/docker
          IMAGE_URI: docker.pkg.github.com/ingo-fp-angel/merkliste_2.0/merkliste_20
          TAG_NAME: ${{ env.VERSION }}
